### ISSUE TITLE
Typo in url 

### ISSUE THREAD

**Issue by litlfred** [WorldHealthOrganization/smart-ig-template-who#2]
package-list.json has a typo at 'who-int' in the URL
https://build.fhir.org/ig/who-ing/ig-template-who

**Comment by guri-dev** [comment]
Has it been fixed or not?

**Comment by litlfred** [comment]
thanks @guri-dev  for reaching out.  I am not sure if this is fixed or not.  @costateixeira ?

**Comment by costateixeira** [comment]
I don't see any reference to this, but the hl7 build site is at https://build.fhir.org/ig/WorldHealthOrganization/ not https://build.fhir.org/ig/who-int, right? github.com/who-int doesn't exist

**Comment by litlfred** [comment]
i think we can close this b/c i didnt see the issue anymore.
